<a href="https://colab.research.google.com/github/vaibhavpathak999/Machine-Learning-Course-/blob/master/ML_1_NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math as m

In [ ]:
a = np.array([5, 1, 2, 1])
a.mean()

2.25

In [ ]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a+2

array([3, 4, 5])

In [ ]:
a**2

array([1, 4, 9], dtype=int32)

In [ ]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
a/b

array([0.25, 0.4 , 0.5 ])

In [ ]:
a.mean()

2.0

sigma(x(i)-x(mean))**2

In [ ]:
deviation=((b-b.mean())**2).sum()
deviation

2.0

sqrt((x(1)-x(2))**2 + (y(1)-y(2))**2 + (z(1)-z(2))**2)

In [ ]:
distance=m.sqrt((((b-a)**2).sum()))
distance

5.196152422706632

In [ ]:
dotProduct = a.dot(b)
dotProduct

32