# Generic Gradient decent for n features from scratch code

# importing the necessary modules
import numpy as np
import pandas as pd

# getting the data to be trained
data3=np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002417_training_boston_x_y_train.csv",dtype=float,delimiter=",")
#excluding the target values from the data to be trained
X=data3[:,0:13]
#adding the column of ones for the constant values
X_CValues1 = np.ones((379,1))
#using the np.concatenate for concatenating the ones column in data values
data1= np.concatenate((X,X_CValues1),axis=1)
#making the target values by slicing
target=data3[:,13:14]
#prining the shapes of target and data values
print(data1.shape,target.shape)

num_iterations=1000
learning_rate = 0.15
m=genericGD(data1,target,learning_rate,num_iterations)

testData = np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002417_test_boston_x_test.csv",delimiter = ",")
PredictValues = predict(testData,m)
np.savetxt('ML_Boton_try.csv', PredictValues, fmt='%.5f', delimiter=',')

def genericGD(data,targets,learning_rate,num_iterations):
    m=np.zeros(14)
    for i in range(num_iterations):
        m=step_GGD(data,targets,learning_rate,m)
        print(i,cost(data,targets,m))
    return m    
        

def step_GGD(data,targets,learning_rate,m):
    dataShape = data.shape
    dataTotalPointsInColumn = dataShape[0]
    dataTotalPointsInRow = dataShape[1]   
    new_m = []
    for k in range(dataTotalPointsInRow):
        newTemp_M_Sum =0
        for i in range(dataTotalPointsInColumn):
            y=targets[i][0] 
            M_Sum=0
            for j in range(dataTotalPointsInRow):
                x=data[i][j]
                M_Sum += x*m[j]
            newTemp_M_Sum += (y - M_Sum)*(-2)*data[i][k]/dataTotalPointsInColumn
        m[k] = m[k] - (learning_rate*newTemp_M_Sum)
        new_m.append(m[k])  
    return new_m          

def cost(data,targets,m):
    total_cost = 0.0
    dataShape = data.shape
    dataTotalPointsInColumn = dataShape[0]
    dataTotalPointsInRow = dataShape[1]
    
    for i in range(dataTotalPointsInColumn):
        temporarySum = 0.0
        for j in range(dataTotalPointsInRow):            
            temporarySum += m[j]*data[i][j] 
        total_cost += (targets[i][0]-temporarySum)**2    
    return (total_cost/dataTotalPointsInColumn)        

def predict(testData,m):
    M,N =testData.shape
    predictions = []
    for i in range(M):
        y=0
        for j in range(N):
            y += m[j]*testData[i][j] 
        #y += testData[i][13]    
        predictions.append(float(y))
    return np.array(predictions)         

print(X_test.shape)

# Combined Power Plant data Analysis with Gradient Descent

import numpy as np
import pandas as pd

# getting the data to be trained
data=np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002419_training_ccpp_x_y_train.csv",dtype=float,delimiter=",")
#excluding the target values from the data to be trained
X=data[:,0:4]
#adding the column of ones for the constant values
X_CValues = np.ones((7176,1))
#using the np.concatenate for concatenating the ones column in data values
data1= np.concatenate((X,X_CValues),axis=1)
#making the target values by slicing
target=data[:,4:5]
#prining the shapes of target and data values
print(data1.shape,target.shape)
print(target[1:5])

X1=data1[:,0:2]
X2=data1[:,2:3]
X2=X2/1000
X3=data1[:,3:5]
dataNor = np.concatenate((X1,X2,X3),axis = 1)
for i in range(5):
    for j in range(5):
        print(dataNor[i][j],end=" ")
    print()    

for i in range(5):
    for j in range(5):
        print(data1[i][j],end=" ")
    print()    

num_iterations=10
learning_rate = 0.1
m=genericGD(dataNor,target,learning_rate,num_iterations)

def genericGD(data,targets,learning_rate,num_iterations):
    m=np.zeros(5)
    for i in range(num_iterations):
        m=step_GGD(data1,targets,learning_rate,m)
        print(i,cost(data,targets,m))
    return m           

def step_GGD(data,targets,learning_rate,m):
    dataShape = data.shape
    dataTotalPointsInColumn = dataShape[0]
    dataTotalPointsInRow = dataShape[1]   
    new_m = []
    for k in range(dataTotalPointsInRow):
        newTemp_M_Sum =0
        for i in range(dataTotalPointsInColumn):
            y=targets[i][0] 
            M_Sum=0
            for j in range(dataTotalPointsInRow):
                x=data[i][j]
                M_Sum += x*m[j]
            newTemp_M_Sum += -2*((y - M_Sum)*data[i][k])/dataTotalPointsInColumn
            
        m[k] = (m[k] - (learning_rate*newTemp_M_Sum))
        new_m.append(m[k])  
    return new_m          

def cost(data,targets,m):
    total_cost = 0.0
    dataShape = data.shape
    dataTotalPointsInColumn = dataShape[0]
    dataTotalPointsInRow = dataShape[1]
    print(dataTotalPointsInColumn)
    print(dataTotalPointsInRow)
    for i in range(dataTotalPointsInColumn):
        temporarySum = 0.0
        for j in range(dataTotalPointsInRow):            
            temporarySum += m[j]*data[i][j] 
        total_cost += (targets[i][0]-temporarySum)**2    
    return (total_cost/dataTotalPointsInColumn)        

def predict(testData,m):
    M,N =testData.shape
    predictions = []
    for i in range(M):
        y=0
        for j in range(N):
            y += m[j]*testData[i][j] 
        predictions.append(float(y))
    return np.array(predictions)         

In [63]:
### getting the data to be trained
#data=np.genfromtxt(r"‪C:\Users\vaibh\Downloads\0000000000002417_training_boston_x_y_train (1).csv",dtype=float,delimiter=",")
#excluding the target values from the data to be trained
data = np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002417_training_boston_x_y_train.csv",dtype=float,delimiter=",")
X=data[:,0:13]
#adding the column of ones for the constant values
X_CValues = np.ones((379,1))
#using the np.concatenate for concatenating the ones column in data values
data1= np.concatenate((X,X_CValues),axis=1)
#making the target values by slicing
target=data[:,13:14]
#prining the shapes of target and data values
print(data1.shape,target.shape)
print(target[1:5])
print(data1)

(379, 14) (379, 1)
[[21.4]
 [12.7]
 [19.9]
 [22.5]]
[[-0.40784991 -0.48772236 -1.2660231  ...  0.41057102 -1.09799011
   1.        ]
 [-0.40737368 -0.48772236  0.24705682 ...  0.29116915 -0.52047412
   1.        ]
 [ 0.1251786  -0.48772236  1.01599907 ... -3.79579542  0.89107588
   1.        ]
 ...
 [-0.40831101 -0.48772236  0.24705682 ...  0.33206621 -0.33404299
   1.        ]
 [-0.41061997 -0.48772236 -1.15221381 ...  0.203235   -0.74475218
   1.        ]
 [ 0.34290895 -0.48772236  1.01599907 ...  0.38787479 -1.35871335
   1.        ]]


In [94]:
# getting the data to be trained
dataCC=np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002419_training_ccpp_x_y_train.csv",dtype=float,delimiter=",")
#excluding the target values from the data to be trained
X=dataCC[:,0:4]
#adding the column of ones for the constant values
X_CCValues = np.ones((7176,1))
#using the np.concatenate for concatenating the ones column in data values
dataCCTrain= np.concatenate((X,X_CCValues),axis=1)
#making the target values by slicing
target=dataCC[:,4:5]
#prining the shapes of target and data values
print(dataCCTrain.shape,target.shape)
print(target[1:5])
print(dataCCTrain)
for i in range(4):
    for j in range(7176):
        if i == 0:
            dataCCTrain[j][i]=dataCCTrain[j][i]/100
        elif i == 1:
            dataCCTrain[j][i]=dataCCTrain[j][i]/100
        elif i == 2:
            dataCCTrain[j][i]=dataCCTrain[j][i]/10000
        elif i == 3:
            dataCCTrain[j][i]=dataCCTrain[j][i]/100 
print(dataCCTrain)         
testData = np.genfromtxt(r"C:\Users\vaibh\Downloads\0000000000002419_test_ccpp_x_test.csv",delimiter = ",")
print()
print(testData)
for i in range(4):
    for j in range(2392):
        if i == 0:
            testData[j][i]=testData[j][i]/100
        elif i == 1:
            testData[j][i]=testData[j][i]/100
        elif i == 2:
            testData[j][i]=testData[j][i]/10000
        elif i == 3:
            testData[j][i]=testData[j][i]/100 

print()
print(testData)

(7176, 5) (7176, 1)
[[446.94]
 [452.56]
 [433.44]
 [480.38]]
[[8.58000e+00 3.83800e+01 1.02103e+03 8.43700e+01 1.00000e+00]
 [2.17900e+01 5.82000e+01 1.01721e+03 6.67400e+01 1.00000e+00]
 [1.66400e+01 4.89200e+01 1.01155e+03 7.87600e+01 1.00000e+00]
 ...
 [2.98000e+01 6.93400e+01 1.00936e+03 6.47400e+01 1.00000e+00]
 [1.63700e+01 5.43000e+01 1.01794e+03 6.36300e+01 1.00000e+00]
 [3.01100e+01 6.20400e+01 1.01069e+03 4.79600e+01 1.00000e+00]]
[[0.0858   0.3838   0.102103 0.8437   1.      ]
 [0.2179   0.582    0.101721 0.6674   1.      ]
 [0.1664   0.4892   0.101155 0.7876   1.      ]
 ...
 [0.298    0.6934   0.100936 0.6474   1.      ]
 [0.1637   0.543    0.101794 0.6363   1.      ]
 [0.3011   0.6204   0.101069 0.4796   1.      ]]

[[  11.95   42.03 1017.58   90.89]
 [  12.07   38.25 1012.67   81.66]
 [  26.91   74.99 1005.64   78.98]
 ...
 [  24.32   66.25 1009.09   91.89]
 [  23.49   42.8  1013.96   65.31]
 [  21.76   60.27 1018.96   85.06]]

[[0.1195   0.4203   0.101758 0.9089  ]
 [0.

In [112]:
learning_rate = 0.15
iterations = 1000
m=g_Descent(dataCCTrain,target,iterations,learning_rate)
print(m)
predictions = predict(testData,m)
np.savetxt('ML_CC_Try.csv', predictions, fmt='%.5f', delimiter=',')
print(predictions)

0 58106.42254371638

1 17049.562285709693

2 5729.867135200822

3 2615.7377091427984

4 1760.6292371915038

5 1524.7223930175887

6 1457.1246155456663

7 1434.542176493125

8 1423.6228498411224

9 1415.5362078435908

10 1408.046903038297

11 1400.6451232395427

12 1393.2465303913473

13 1385.8572873501307

14 1378.4943316260326

15 1371.1701062518025

16 1363.891894532953

17 1356.6635022340877

18 1349.4867015466734

19 1342.362143680752

20 1335.2898803565033

21 1328.2696490933001

22 1321.3010260269862

23 1314.3835068779035

24 1307.516549582817

25 1300.699596641964

26 1293.9320867793788

27 1287.213460986288

28 1280.5431656164333

29 1273.9206539356435

30 1267.3453868618367

31 1260.816833281711

32 1254.334470146726

33 1247.8977824545457

34 1241.5062631717744

35 1235.1594131270404

36 1228.856740889814

37 1222.5977626428648

38 1216.3820020526152

39 1210.2089901394677

40 1204.0782651493266

41 1197.9893724267506

42 1191.9418642901348

43 1185.9352999089758

44 1179.96

In [106]:
def g_Descent(data,targets,iterations,learning_rate):
    m=np.zeros(5)
    for i in range(iterations):
        m=step_Descent(data,targets,learning_rate,m)
        print(i,cost(data,targets,m))
        print()
    return m    

In [68]:
def step_Descent(data,targets,learning_rate,m):
    X,Y = data.shape
    for i in range(Y):
        Total_Sum = 0
        for j in range(X):
            y=targets[j]
            row_Sum =0
            for k in range(Y):
                row_Sum += m[k]*data[j][k]
            Total_Sum += (-2/X)*data[j][i]*(y-row_Sum)
        m[i] -= learning_rate*Total_Sum
    return m    

In [69]:
def cost(data,targets,m):
    total_cost = 0
    X,Y=data.shape
    for i in range(X):
        temp_cost = 0
        for j in range(Y):
            temp_cost += data[i][j]*m[j]  
        total_cost += ((targets[i][0] - temp_cost)**2)
    return (total_cost/X)    

In [109]:
def predict(testData,m):
    M,N =testData.shape
    predictions = []
    for i in range(M):
        y=0
        for j in range(N):
            y += m[j]*testData[i][j] 
        y += m[4]    
        predictions.append(float(y))
    return np.array(predictions)         